### PR TITLE
22882 - Court order notification.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:22882 *https://github.com/bcgov/entity/issues/22882 

*Description of changes:*
 Court order notification for filing history

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-29-npit7bxw.web.app

**Comment by hfekete** [comment]
> Temporary Url for review: https://business-dashboard-dev--pr-29-npit7bxw.web.app

can use BI for test: BC0871220

**Review by kialj876 — APPROVED** [review]
Nice

**Pull request merged**
