### PR TITLE
Fix for documents not loading when hitting details instead of show/hide

### PR DESCRIPTION
**Pull request by BrandonSharratt**
*Issue:*https://github.com/bcgov/entity/issues/24662

*Description of changes:*
Change so that pressing detail also calls the api for document list

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by BrandonSharratt** [comment]
gcbrun

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-100-9rthscco.web.app

**Review by hfekete — APPROVED** [review]
nice!

**Pull request merged**
