### PR TITLE
24817 - fix: wrong redirect; missing start date for filings.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:*https://github.com/bcgov/entity/issues/

*Description of changes:*

fix:
- wrong redirect
- missing start date for filings.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-107-2hg89hb1.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-107-2hg89hb1.web.app

**Review by patrickpeinanw — APPROVED** [review]
LGTM

**Pull request merged**
