### PR TITLE
Template Flip - Two file flips

### PR DESCRIPTION
**Pull request by BrandonSharratt**
*Issue:*https://github.com/bcgov/entity/issues/

*Description of changes:*
This just flips two files to the new standard of script -> template from template -> script

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-24-lmdws8qj.web.app

**Review by patrickpeinanw — APPROVED** [review]
Thanks for the update. Can you fix the lint errors before merging?

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-24-lmdws8qj.web.app

**Pull request merged**
