### PR TITLE
UI - staff filing options

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/21787

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-50-33ig9t6x.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-50-33ig9t6x.web.app

**Review by hfekete — APPROVED** [review]
Nice, looks good!
Did a quick scan and could not find any issues.

**Comment by hfekete** [comment]
Just before merging in, make sure tests are passing

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-50-33ig9t6x.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-50-33ig9t6x.web.app

**Pull request merged**
