### PR TITLE
Apply i18n to todo section

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/22892
*Description of changes:*
- apply 18n text for todo sections 
- implement i18n-helper component for bold and link

This is a screenshot taken from the cypress e2e test, showing that i18n-helper can handle bold text
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-30-2608de2n.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-30-2608de2n.web.app

**Review by hfekete — APPROVED** [review]
Thanks for doing this. And thx for putting comment on the helper component

**Pull request merged**
