### PR TITLE
Todo actions: Draft, Pending, and Error filing

### PR DESCRIPTION
**Pull request by patrickpeinanw**
*Issue:*https://github.com/bcgov/entity/issues/22255
*Issue:*https://github.com/bcgov/entity/issues/22256

*Description of changes:*
- Todo Filing: DRAFT, PENDING, ERROR

Summary of the Todo Section:
https://docs.google.com/spreadsheets/d/1rJY3zsrdHS2qii5xb7hq1gt-D55NsakJtdu9ld9d80U/edit?gid=1817132924#gid=1817132924

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-23-qip27f59.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-23-qip27f59.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-23-qip27f59.web.app

**Review by kialj876 — APPROVED** [review]
Really nice work Patrick. Thanks for walking me through it earlier

**Pull request merged**
