### PR TITLE
Fix which modal shows

### PR DESCRIPTION
**Pull request by BrandonSharratt**
*Issue:*https://github.com/bcgov/entity/issues/24459
https://github.com/bcgov/business-dashboard-ui/pull/78

*Description of changes:*
Change the condition for the modal to include staff  when not in good standing to fix which dialog shows

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-81-mj3bn1kv.web.app

**Comment by severinbeauvais** [comment]
I'm still seeing this when I click View and Change Business Information:

image

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-81-mj3bn1kv.web.app

**Comment by severinbeauvais** [comment]
> I'm still seeing this when I click View and Change Business Information:

Hey, it works now.

**Review by severinbeauvais — APPROVED** [review]
LGTM but you have a broken test.

**Pull request merged**
