### PR TITLE
24755 - fix: when and how is account fetched.

### PR DESCRIPTION
**Pull request by hfekete**
*Issue:24755*https://github.com/bcgov/entity/issues/24755

*Description of changes:*
fix: when and how is account fetched.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-dashboard-dev--pr-98-dnwl9ptp.web.app

**Review by BrandonSharratt — APPROVED** [review]
This fixes the requested ticket and looks good to me. I do wish that the account selector would be enabled on the error page when one account has access and you happen to be in one that doesn't but that is out of scope for this ticket and covered in a different ticket.

**Comment by severinbeauvais** [comment]
LGTM

**Pull request merged**
